apps/analyses/urls.py
from django.urls import path
from .views import sentiment_analysis, analyze_text


urlpatterns = [
    path('sentiment/', sentiment_analysis, name='sentiment_analysis'),
    path('analyze_text/', analyze_text, name='analyze_text'),
]

apps/data_visualization/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

apps/frontend/urls.py
from django.urls import path
from .views import show_text_input_form

urlpatterns = [
    path('submit-text/', show_text_input_form, name='submit_text_form'),
]

apps/user_inputs/urls.py
from django.urls import path
from .views import text_input

urlpatterns = [
    path('text/', text_input, name='text_input'),
]

truth_will_set_you_free/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('analyses/', include('apps.analyses.urls')),
    path('', views.home, name='home'),
    path('frontend/', include('apps.frontend.urls')),
    path('user_inputs/', include(('apps.user_inputs.urls', 'user_inputs'), namespace='user_inputs')),
    path('data_visualization/', include(('apps.data_visualization.urls', 'data_visualization'), namespace='data_visualization')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/analyses/models.py
from django.db import models

class TextAnalysis(models.Model):
    original_text = models.TextField()
    analyzed_text = models.TextField(blank=True)
    analysis_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.original_text[:50]

apps/commands/models.py
from django.db import models

# Create your models here.

apps/user_inputs/models.py
from django.db import models


class UserInput(models.Model):
    text_input = models.TextField()

apps/analyses/forms.py
from django import forms

class TextForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea, required=True, label='Enter text for analysis')

apps/frontend/forms.py
from django import forms
from apps.user_inputs.models import UserInput

class TextInputForm(forms.ModelForm):
    class Meta:
        model = UserInput
        fields = ['text_input']

apps/user_inputs/forms.py
from django import forms


class TextInputForm(forms.Form):
    text_input = forms.CharField(label='Enter text', max_length=100)

apps/analyses/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .forms import TextForm
from django.views.decorators.http import require_http_methods
from .modules.sentiment_analysis import SentimentAnalysis
from .modules.nlp_analysis import analyze_text as nlp_analyze_text

import logging

logger = logging.getLogger(__name__)


def custom_404_view(request, exception):
    logger.error(f"404 error: {exception}, Path: {request.path}")
    return render(request, '404.html', {}, status=404)


def sentiment_analysis(text):
    if text:
        sentiment_analyzer = SentimentAnalysis()
        result = sentiment_analyzer.analyze(text)
        return result
    else:
        return {'error': 'No text provided'}


def analyze_text(request):
    if request.method == "POST":
        form = TextForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            nlp = spacy.load("en_core_web_sm")
            doc = nlp(text)
            tokens_pos = [(token.text, token.pos_) for token in doc]
            analyzed_text = ", ".join([f"{t[0]} ({t[1]})" for t in tokens_pos])

            # Save analysis results
            analysis = TextAnalysis(original_text=text, analyzed_text=analyzed_text)
            analysis.save()

            # Return JSON response
            return JsonResponse({'analysis': analyzed_text})

    # Handle non-POST requests or invalid form submissions
    return JsonResponse({'error': 'Invalid request'}, status=400)

apps/commands/views.py
from django.shortcuts import render

# Create your views here.

apps/data_visualization/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'data_visualization/index.html')

apps/frontend/views.py
from django.shortcuts import render
from .forms import TextInputForm


def show_text_input_form(request):
    form = TextInputForm()
    return render(request, 'text_input_form.html', {'form': form})

apps/nlp_analysis/views.py
from django.shortcuts import render, redirect
from .forms import TextForm
from .models import TextAnalysis
import spacy

def analyze_text(request):
    if request.method == "POST":
        form = TextForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            nlp = spacy.load("en_core_web_sm")
            doc = nlp(text)
            tokens_pos = [(token.text, token.pos_) for token in doc]
            analyzed_text = ", ".join([f"{t[0]} ({t[1]})" for t in tokens_pos])
            analysis = TextAnalysis(original_text=text, analyzed_text=analyzed_text)
            analysis.save()
            return render(request, "nlp_analysis/results.html", {"analysis": analysis})
    else:
        form = TextForm()
    return render(request, "nlp_analysis/index.html", {"form": form})

apps/user_inputs/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods


@require_http_methods(["POST"])
def text_input(request):
    text_content = request.POST.get('text')

    if text_content:
        # Perform analysis on text_content...
        analysis_result = analyze_text(text_content)  # Implement this function
        return JsonResponse(analysis_result)

    # Handle error case, possibly with a custom error message or status code
    return JsonResponse({'error': 'No text provided'}, status=400)

truth_will_set_you_free/views.py
from django.shortcuts import render
from apps.user_inputs.forms import TextInputForm


def home(request):
    # Render a template or return a response
    return render(request, 'home.html')

apps/data_visualization/templates/data_visualization/index.html
<!DOCTYPE html>
{% load static %} <!-- This needs to be at the top after the DOCTYPE declaration -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Visualization</title>
    <link rel="stylesheet" href="{% static 'data_visualization/css/style.css' %}">
</head>
<body>
    <canvas id="webgl-canvas" width="640" height="480"></canvas>

    <script src="{% static 'data_visualization/dist/bundle.js' %}"></script>
</body>
</html>

apps/frontend/templates/text_input_form.html
<form action="{% url 'user_inputs:text_input' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Text</button>
</form>

templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Analysis Home</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'data_visualization/css/style.css' %}">
</head>
<body>
    <header>
        <h1>Text and Video Analysis</h1>
    </header>
    
    <main>
        <section id="text-input-section">
            <h2>Submit Text for Analysis</h2>
            <form id="text-analysis-form">
                {% csrf_token %}
                <textarea id="text-input" name="text_input" placeholder="Enter text here..."></textarea>
                <button type="button" id="analyze-button">Analyze Text</button>
            </form>
        </section>
        
        <form id="text-analysis-form">
            {% csrf_token %}
            <textarea id="text-input" name="text_input" placeholder="Enter text here..."></textarea>
            <button type="button" id="analyze-button">Analyze Text</button>
        </form>

        
        <section id="text-analysis-results">
            <h2>Text Analysis Results</h2>
            <div id="text-results-container">Textual results will be displayed here.</div>
        </section>
        
        <section id="visualization-results">
            <h2>Visualization Results</h2>
            <canvas id="webgl-canvas" width="640" height="480"></canvas>
            <img id="visualization-image" src="" alt="Visualization will appear here" style="display:none;">
        </section>
    </main>
    <div id="status-message"></div>
    <footer>
        <p>© 2024 Analysis Tool</p>
    </footer>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/websocket_handlers.js' %}"></script>
    <script src="{% static 'data_visualization/dist/bundle.js' %}"></script>
</body>

<script>
document.getElementById('analyze-button').addEventListener('click', function() {
    var textInput = document.getElementById('text-input').value;
    var csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    var formData = new FormData();
    formData.append('text', textInput); // Ensure the field name matches your form

    fetch("/analyze_text/", {  // Adjust URL as needed
        method: 'POST',
        body: formData,
        headers: {"X-CSRFToken": csrfToken}
    })
    .then(response => response.json())
    .then(data => {
        if(data.analysis) {
            document.getElementById('text-results-container').innerHTML = data.analysis;
        } else {
            document.getElementById('text-results-container').innerHTML = "Analysis failed. Please try again.";
        }
    })
    .catch(error => console.error('Error:', error));
});
</script>

</html>